### ISSUE TITLE
discuss the data

### ISSUE THREAD

**Issue by nanjingyige** [waxnkw/gvcnn-pytorch#2]
[
    [the-path-to-train-image/xxx_, label-of-this-img],
    [the-path-to-train-image/yyy_, label-of-this-img],
    [the-path-to-train-image/zzz_, label-of-this-img],
    ......
]我想问下这个xxx_yyy_,zzz_代表着什么意思

**Comment by waxnkw** [comment]
这个是代表 "xxx_001.jpg" 把 "001.jpg" 后缀去掉。 因为我是参加了一个比赛，那个数据格式可能和常用数据集上的命名格式之类的不一样，所以我就把数据部分脚本删了。你用的什么数据集，大概文件夹结构是什么样的，能不能给我张截图。我周末有空的话补一下这一部分。

**Comment by nanjingyige** [comment]
我用的就是modelnet40 转化成12个视图的数据集，你用的是什么数据集呀？还有你这个代码不是对作者论文gvcnn的复现嘛

**Comment by nanjingyige** [comment]
如果能补充下，真的是太感谢了！🙏

**Comment by waxnkw** [comment]
好的，我有空补一下。我不是完全复现的，我稍微改了两个地方，我在README里面也写了，你可以用的时候改一改。

**Comment by nanjingyige** [comment]
非常感谢🙏

**Comment by waxnkw** [comment]
我补上了，但是不保证正确，你试试，有问题我再改

**Comment by nanjingyige** [comment]
hello!can you improve your task's accuracy with this code?I run this code on modelnet40 many times,but the best result is 90.25%,which is far away from paper's 92.2%。I can also achieve 90.1% using MVCNN(pytorch).

**Comment by nanjingyige** [comment]
thank you for your code!

**Comment by waxnkw** [comment]
我是参加了一个比赛，我没跑过modelnet40。我改了原文两个小地方，我不知道是不是因为这个导致的跑的没有那么好。你可以改回来试试。
